export const courses = [
  {
    id: "sql", badge: "SOURCE COURSE 01", title: "SQL: From First Query to Database Builder", source: "Built from the SQL source book", description: "Learn to read, question, summarize, connect, and safely change relational data.",
    modules: [
      ["Start with tables", "What a database, table, row, column, field, record, primary key, and result set actually are.", ["Map a Customers table in plain English.", "Tell a row from a column without guessing.", "Identify the key that makes one record unique."], "Draw a table with `student_id`, `name`, and `city`. Which column should uniquely identify one student?", "student_id", "A primary key is a stable unique identifier; names can repeat or change."],
      ["Ask your first question", "SELECT, FROM, and the difference between requesting all columns and selecting only what you need.", ["Read a SELECT query as an English sentence.", "Choose specific columns on purpose.", "Explain why a SELECT query does not change data."], "Which clause tells SQL which table provides the rows?", "FROM", "FROM identifies the source table."],
      ["Filter without losing the question", "WHERE, comparison operators, AND, OR, NOT, IN, BETWEEN, and LIKE patterns.", ["Translate a real question into a condition.", "Predict whether AND narrows or broadens a result.", "Use parentheses when conditions are mixed."], "Which operator requires every linked condition to be true?", "AND", "AND keeps a row only when every connected condition is true."],
      ["Sort and limit results", "ORDER BY, ascending and descending order, TOP/LIMIT differences, and why predictable output matters.", ["Sort a result by one and then two columns.", "Read ASC and DESC correctly.", "Limit a result only after deciding how it should be ordered."], "Why should you choose ORDER BY before limiting a result?", "Because otherwise the chosen rows may not be the rows you meant to inspect.", "A limit without a defined order can return an arbitrary-looking slice."],
      ["Add and update safely", "INSERT INTO, UPDATE, and the read-first safety habit.", ["Name columns when inserting a row.", "Use WHERE with UPDATE.", "Run a matching SELECT before making a change."], "What should you run before an UPDATE that uses WHERE?", "A SELECT with the same WHERE condition", "It lets you inspect exactly which rows will change."],
      ["Delete with intention", "DELETE, emptying a table, and why destructive practice belongs in sample databases only.", ["Distinguish deleting selected rows from every row.", "Explain why a missing WHERE is dangerous.", "Write the matching SELECT safety check."], "What does DELETE without WHERE target?", "Every row in the table", "A WHERE clause is what narrows the deletion."],
      ["Find patterns and ranges", "MIN, MAX, COUNT, AVG, SUM, DISTINCT, aliases, text patterns, and range questions.", ["Use an alias to name a calculated answer.", "Choose COUNT versus DISTINCT COUNT.", "Use LIKE and BETWEEN for the right kind of question."], "Which function counts rows that meet a condition?", "COUNT", "COUNT summarizes how many matching rows exist."],
      ["Summarize by category", "GROUP BY and HAVING: turning individual records into meaningful category-level answers.", ["Group device outages by location.", "Explain WHERE before grouping and HAVING after grouping.", "Read a count alias in a result."], "Which clause filters an aggregate after COUNT has been calculated?", "HAVING", "HAVING evaluates group summaries; WHERE filters individual rows first."],
      ["Connect related tables", "Keys, INNER/LEFT/RIGHT/FULL joins, self joins, and UNION.", ["State the relationship before writing a join.", "Choose a join based on whether unmatched rows matter.", "Spot a duplicate-producing join."], "What does an INNER JOIN return?", "Rows with matches on both sides", "An INNER JOIN keeps records that satisfy the matching condition in both tables."],
      ["Build the database", "CREATE/DROP databases and tables, ALTER TABLE, data types, constraints, indexes, auto increment, views, procedures, and safe hosting.", ["Create a table with a key and required field.", "Explain why constraints protect data quality.", "Choose an index only for a question you actually need to speed up."], "Which constraint prevents a required column from being left empty?", "NOT NULL", "NOT NULL protects a required field from missing values."],
      ["Defend the database", "NULL handling, SQL comments, operators, dates, parameterized queries, injection awareness, and permissions.", ["Tell NULL from an empty string.", "Write a comment that explains a decision.", "Explain why user input must never be glued into a query string."], "What is the safe default for user-provided values in a query?", "Use parameterized queries", "Parameters keep data separate from SQL instructions."],
      ["SQL capstone: decision lab", "Use a small safe dataset to answer a decision question and explain your evidence.", ["Write the question before the query.", "Build a read-only query sequence.", "Publish a README with a finding and limitation."], "What makes a data finding trustworthy?", "A clear question, inspectable query, result, and stated limitation", "A result needs context and an honest boundary, not just a number."],
    ]
  },
  {
    id: "network", badge: "SOURCE COURSE 02", title: "Python Network Automation: Lab to Production", source: "Built from Mastering Python Network Automation", description: "Build safe automation habits before moving from Python fundamentals to devices, containers, and service mesh systems.",
    modules: [
      ["Python essentials for networks", "Data types, loops, functions, arguments, scope, lambdas, and reusable automation thinking.", ["Choose a list or dictionary for device information.", "Trace a loop through an inventory.", "Return a reliable result from a small function."], "What should a function return when another part of the program needs its answer?", "A value", "Returning lets later code test, store, or act on the result."],
      ["Files, modules, and reliable scripts", "Read, write, append, use with blocks, handle exceptions, and organize reusable modules and packages.", ["Save a report safely.", "Explain a file error instead of hiding it.", "Separate helpers from the main workflow."], "Why use `with open(...)` for a file?", "It closes the file safely when the block ends", "The context manager handles the resource lifecycle."],
      ["Prepare a safe automation lab", "Network devices, emulators, Python environments, virtual environments, NS-3, VS Code, and first read-only scripts.", ["Separate practice from production equipment.", "Create a project virtual environment.", "Choose a harmless first test."], "What is the safest first action in a new network automation lab?", "Collect read-only status", "Read-only checks validate assumptions without changing devices."],
      ["Choose and configure libraries", "Nornir, Paramiko, Netmiko, PyEZ, ports, hosts, servers, encryption, and connectivity testing.", ["Explain which library layer fits an SSH task.", "Test host, port, and SSH connectivity separately.", "Keep credentials and device data out of code."], "Why test connectivity in layers?", "It isolates the failing part", "A host may respond while a port, credential, or library setup still fails."],
      ["Code, test, and validate automation", "Inventories, tasks, playbooks, test cases, debugging, result documentation, and a production validation gate.", ["Break an automation task into inputs, action, and expected output.", "Write a normal and edge test case.", "Document evidence before production."], "What belongs in a reproducible bug report?", "Input, expected result, actual result, and repeatable steps", "Evidence lets another person find the same problem."],
      ["Configuration management", "Terraform provisioning, Python system settings, base configurations, inventory, updates, patches, and compliance checks.", ["State desired configuration before changing anything.", "Compare running state with the expected baseline.", "Plan reversible updates."], "What is configuration drift?", "Actual settings no longer match the intended baseline", "Drift is the gap configuration management tries to detect and correct."],
      ["Docker and container networks", "Containers, Dockerfiles, images, Docker SDK, container lifecycle, and network management.", ["Tell an image from a running container.", "Read a Dockerfile as a recipe.", "Collect container facts before changing a network."], "What is a Docker image?", "A reusable blueprint for containers", "Containers are running instances created from images."],
      ["Orchestrate workloads", "Scheduling, service discovery, etcd, HAProxy, certificates, storage, monitoring, and rolling updates.", ["Explain why service discovery exists.", "Define a health signal before automation.", "Plan a rolling update with a rollback condition."], "Why are rolling updates safer than replacing everything at once?", "They limit blast radius and allow verification in stages", "A staged rollout makes failure easier to detect and contain."],
      ["Pod networking and policy", "Pods, Calico, Cilium, routing, network policies, workload routing, and least-privilege communication.", ["Name the difference between a pod and a service.", "Write a policy goal in plain language.", "Test allowed and denied traffic."], "What should a network policy describe?", "Which communication is allowed", "A policy is an explicit rule, not a vague security wish."],
      ["Service mesh and observability", "Service-to-service communication, Istio, cluster traffic, control planes, metrics, logs, traces, and Grafana.", ["Distinguish a metric, log, and trace.", "Choose evidence for a latency problem.", "Connect traffic routing changes to observability."], "Which observability signal follows one request across services?", "A trace", "Traces connect work across service boundaries."],
      ["Network capstone: health reporter", "Build a safe inventory reporter with tests, a report file, documented limitations, and an improvement plan.", ["Use fake devices and sample credentials only.", "Validate missing or malformed data.", "Publish code and a safe README."], "What makes the capstone safe to share?", "Fake data, no secrets, tests, and clear documentation", "A public project should prove skill without exposing infrastructure."],
    ]
  },
  {
    id: "data", badge: "SOURCE COURSE 03", title: "Data Science: Think Clearly, Model Carefully", source: "Built from the Data Science archive", description: "Turn a large collection of data-science concepts into a connected, beginner-to-advanced reasoning path.",
    modules: [
      ["Data before models", "Data frames, data types, missing values, summary statistics, sampling, and why a quick description can mislead.", ["Inspect shape and types first.", "Separate missingness from a numeric zero.", "Ask which rows may be absent from the data."], "Why can mean imputation be risky?", "It can hide patterns and reduce variation", "A convenient fill value may change the story the data tells."],
      ["Statistics with judgment", "Correlation limits, distributions, conditional probability, likelihood, confidence intervals, prediction intervals, and normality checks.", ["State what a statistic does not prove.", "Tell probability from likelihood.", "Choose an interval based on the question."], "Does correlation alone prove causation?", "No", "Correlation describes association, not the cause of that association."],
      ["Visualize the right story", "Histograms, heatmaps, scatter alternatives, rainclouds, waterfall and bump charts, and decluttered plotting.", ["Match a chart to the decision.", "Label the comparison and its unit.", "Check whether the chart hides distribution or uncertainty."], "What should a chart make clear before it looks pretty?", "The comparison and scale", "A beautiful chart can still mislead if the reader cannot see what is being compared."],
      ["Prepare features responsibly", "Scaling, normalization, log transforms, categorical encoding, one-hot limitations, and validation of the outcome variable.", ["Ask whether a transformation is necessary.", "Recognize category explosion.", "Keep preprocessing inside the evaluation pipeline."], "Why fit preprocessing only on training data?", "To prevent information leakage", "Using test information during preparation makes evaluation look better than real use."],
      ["Linear models and regression", "OLS, regularization, Poisson regression, R-squared limits, feature importance, and error measures.", ["State the prediction target.", "Inspect residual and error behavior.", "Name a limitation of a single metric."], "Why can R-squared be insufficient alone?", "It does not reveal every kind of error or misuse", "A model needs context, error inspection, and a decision-appropriate metric."],
      ["Classification and evaluation", "Discriminative models, logistic regression, sigmoid, precision, recall, confusion matrices, imbalance, and loss functions.", ["Define the positive class.", "Compare false positives with false negatives.", "Choose a threshold based on cost."], "What does recall measure?", "How many real positives were found", "Recall focuses on coverage of the positive cases."],
      ["Validation and reproducibility", "Train/validation/test splits, cross-validation, random seeds, reproducibility limits, grid search, and random search.", ["Keep a final test set untouched.", "Record split, seed, and preprocessing choices.", "Avoid choosing a model by repeatedly peeking at the test set."], "Why keep a final test set separate?", "To estimate performance on unseen data honestly", "Repeated tuning against it turns the test set into part of training."],
      ["Trees, ensembles, and boosting", "Decision trees, overfitting, random forests, bagging, boosting, feature importance, and evaluation without labels.", ["Recognize a tree that memorizes noise.", "Compare independent trees with sequential boosting.", "Use validation evidence before trusting feature rankings."], "Why do decision trees often need constraints?", "They can overfit training data", "Unconstrained splits can memorize details that will not repeat."],
      ["Clustering and distance", "KMeans, Gaussian mixtures, DBSCAN, silhouette limits, epsilon selection, distance choices, and clustering without ground truth.", ["State the geometry you assume.", "Inspect cluster meaning instead of trusting a score.", "Know when density methods fit better than centroid methods."], "Why can silhouette score be incomplete?", "It evaluates separation but not whether clusters are meaningful for the problem", "A numerical score is not a substitute for domain reasoning."],
      ["Dimensionality and embeddings", "PCA, static embeddings, multiple embedding models, dimensions, locality, and visualization tradeoffs.", ["Explain variance versus meaning.", "Check what is lost in reduction.", "Avoid treating a 2D picture as the full data structure."], "What does PCA trade for a smaller representation?", "Some information and interpretability", "Reduction keeps selected variation while discarding other detail."],
      ["Neural networks and optimization", "Linearly inseparable data, neural transformations, gradients, batch sizes, checkpointing, and memory/performance tradeoffs.", ["Trace input, hidden representation, and output.", "Compare batch, mini-batch, and stochastic updates.", "Explain why a training score can be misleading."], "Why is validation behavior important during training?", "It checks whether learning generalizes beyond training examples", "Training improvement alone can hide overfitting."],
      ["Professional data workflow", "Pandas versus Polars, vectorization, I/O, notebook organization, EDA tools, reproducible scripts, and clean communication.", ["Avoid slow row-by-row habits when a vectorized operation fits.", "Separate exploration from a reproducible final workflow.", "Document data source, assumptions, and limitations."], "What makes analysis reproducible?", "Recorded data, steps, environment, and assumptions", "Another person needs enough context to rerun and evaluate the work."],
      ["Data capstone: decision memo", "Clean a public dataset, answer a narrow question, choose an honest visualization and metric, then write a limitation-aware recommendation.", ["State the decision and stakeholder.", "Keep an evidence trail from raw data to chart.", "Publish only data you have permission to share."], "What belongs beside a data recommendation?", "Its evidence, uncertainty, and limitation", "Responsible analysis makes its boundaries visible."],
    ]
  }
];
